### PR TITLE
Pipeline integration

### PR DESCRIPTION
**Pull request by ybroeker**
Add Symbol to allow easier usage in pipelines.

### CODE REVIEW

**Comment by olivergondza** [comment]
Please unit add tests verifying the functionality.

**Comment by ybroeker** [comment]
Any updates on this?

**Comment by oleg-nenashev** [comment]
@olamy it would be great to get it released

**Comment by oleg-nenashev** [comment]
Uhm, apparently I can also do it 🤦‍♂  Will probably cut a release after FOSDEM

**Comment by olamy** [comment]
I can't release it https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-javadoc.yml

**Pull request merged**
